### ISSUE TITLE
Sitemap for Xoops 2.5.9

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules26x/xoositemap#5]
Can you make this module compatible with Xoops 2.5.9?

This module is asked here (even if it's in an off topic):
http://xoops.org/modules/newbb/viewtopic.php?post_id=362458#362458

for example.

**Comment by mambax7** [comment]
No. 
Please use: https://github.com/XoopsModules25x/xsitemap

**Comment by cesagonchu** [comment]
Ok.
